name: CI Fuzz

on:
  pull_request:
    branches: [ master ]

env:
  FUZZING_SERVER_ADDRESS: app.code-intelligence.com:6773
  WEB_APP_ADDRESS:  https://app.code-intelligence.com


jobs:
  fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
        working-directory: ${{ github.workspace }}
      - id: start-fuzzing
        name: Build and Instrument
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CIFUZZ_API_TOKEN }}
          project: ${{ env.PROJECT_ID }}
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
      - id: monitor-fuzzing
        name: Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CIFUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: save-results
        name: Save Fuzz Test Results
        uses: CodeIntelligenceTesting/github-actions/save-results@v3
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          ci_fuzz_api_token: ${{ secrets.CIFUZZ_API_TOKEN }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          project: ${{env.PROJECT_ID}}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: upload-artifact
        uses: actions/upload-artifact@v2
        if: ${{ (success() || failure()) }}
        with:
          name: ci_fuzz_results
          path: | 
            findings.json
            coverage.json
            web_app_address.txt